# Generated by Django 4.2 on 2023-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reaction_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='representative_color',
            field=models.CharField(default='secondary', max_length=10),
        ),
    ]
