# Generated by Django 4.2 on 2023-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_topic_representative_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Required, unique and 20 charcters maximum', max_length=255, unique=True, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=255, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(help_text='Required and unique', max_length=255, verbose_name='Comment Title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='Required and unique', max_length=30, unique=True, verbose_name='Topic Title'),
        ),
    ]
