# Generated by Django 4.2 on 2023-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_article_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Change make article featured on index(home) page', verbose_name='Make article Featured'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(blank=True, choices=[('like', '👍'), ('love', '😍'), ('laugh', '😂'), ('surprised', '😮'), ('angry', '😡'), ('sad', '😢')], help_text='Required', max_length=255, null=True, verbose_name='Reaction Choices'),
        ),
    ]
