# Generated by Django 4.2 on 2023-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_like_delete_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload Article Image', upload_to='images/articles/', verbose_name='Article Preview Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Change make article featured on index(home) page', verbose_name='Make Article Featured'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Required and unique', max_length=150, unique=True, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Message must not exceed 255 characters', max_length=255, verbose_name='Comment Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(help_text='Comment Title', max_length=255, verbose_name='Comment Title'),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change like visibility', verbose_name='Like visibility'),
        ),
        migrations.AlterField(
            model_name='like',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Like safe URL'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='representative_color',
            field=models.CharField(default='secondary', help_text='Color for display of Topic to site visitors', max_length=10, verbose_name='Representive Color for Topic'),
        ),
    ]
