# Generated by Django 4.2 on 2023-07-11 19:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False, help_text='Change make article featured on index(home) page', verbose_name='Make Article Featured')),
                ('title', models.CharField(help_text='Required and unique', max_length=150, unique=True, verbose_name='Article Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Article safe URL')),
                ('body', ckeditor.fields.RichTextField(unique=True, verbose_name='Write your Article')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload Article Image', upload_to='images/articles/', verbose_name='Article Preview Image')),
                ('is_active', models.BooleanField(default=True, help_text='Change topic visibility', verbose_name='Topic visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Comment Title', max_length=255, verbose_name='Comment Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Comment safe URL')),
                ('body', models.TextField(help_text='Message must not exceed 255 characters', max_length=255, verbose_name='Comment Body')),
                ('is_active', models.BooleanField(default=True, help_text='Change comment visibility', verbose_name='Comment visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.article')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=30, unique=True, verbose_name='Topic Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Topic safe URL')),
                ('description', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Topic Description')),
                ('representative_color', models.CharField(default='secondary', help_text='Color for display of Topic to site visitors', max_length=10, verbose_name='Representive Color for Topic')),
                ('is_active', models.BooleanField(default=True, help_text='Change topic visibility', verbose_name='Topic visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.BooleanField(default=True, help_text='Like/Dislike', verbose_name='Like/Dislike')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Like safe URL')),
                ('is_active', models.BooleanField(default=True, help_text='Change like visibility', verbose_name='Like visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.article')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.topic')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.topic', verbose_name='Choose a Topic'),
        ),
    ]
